servel:
  active: false
  checkinterval: 1
  url: xxx  
telegram:
  channel: 'xxx'
  token: xxx
vimeo:
  active: true
  checkinterval: 1
  latestdate: "2020-09-24 00:00:00"
  token: xxx
  userid: cntvchile
